const express = require('express')

### GETTING ALL LISTS
GET http://localhost:3000/lists/

### CREATING A NEW LIST
POST http://localhost:3000/lists
Content-Type: application/json

{"title": "List"}

### GET LIST BY SPECIFIC ID
GET http://localhost:3000/lists/65cc0b300034dd14acb650c5

###
PUT 


### UPDATING LIST TITLE BY ID
PATCH http://localhost:3000/lists/65cc0b300034dd14acb650c5
Content-Type: application/json

{"title": "List2"}

### ADDING ITEMS TO LIST BY ID
POST http://localhost:3000/lists/65ce725af95eb2529283a72a/items
Content-Type: application/json

{"name": "Ice Cream",
"quantity": 2,
"purchased": true 
}
